### PR TITLE
Use GTOID instead of PBGitSHA class

### PR DESCRIPTION
**Pull request by 5sw**
The PBGitSHA class was almost identical to the GTOID class from Objective-Git so I removed that and use GTOID instead.

This required some changes in Objective-Git (pull request: https://github.com/libgit2/objective-git/pull/206) to make it NSCopying-compliant.

### CODE REVIEW

**Comment by 5sw** [comment]
Updated with latest changes from master.

**Comment by rowanj** [comment]
Looking to merge this, but it seems to break some of the history.js (parent links)

**Comment by 5sw** [comment]
I can take a look at this.

**Comment by 5sw** [comment]
Ok, updated my branch with the latest code from master, fixed some new PBGitSHA references that appeared since then and fixed the parent links in history.js.

**Comment by rowanj** [comment]
Sounds great :thumbsup:

**Pull request merged**
