### PR TITLE
Add support to collapse and expand a diff

### PR DESCRIPTION
**Pull request by afh**
This is especially useful in the history view for large commits with
long changes in many files so that only the changes that are of interest
are shown.

### CODE REVIEW

**Comment by afh** [comment]
Thanks for merging.

**Comment by hswolff** [comment]
awesome addition!  :D

**Comment by rowanj** [comment]
I hope to put out a build tonight ( approx T -12h ); I'd love if somebody could confirm that the open/close animations I added work as expected.

@afh  @hswolff

**Comment by hswolff** [comment]
Can do.

**Comment by hswolff** [comment]
I'm seeing them open and close as expected.  Not a huge fan of the fade in/out animation, I'd prefer for them to just slide up/down but that's just a preference.

**Comment by Uncommon** [comment]
At first I thought it didn't work because clicking the arrow has no effect. You have to click the path.

**Comment by hswolff** [comment]
Aye that should probably click for both arrow and path.  Also is it my imagination or did the path change color?

**Comment by Uncommon** [comment]
It's now an anchor element to make it clickable, so it looks like a link. I think that could easily be fixed in the CSS.

**Comment by hswolff** [comment]
Glad it wasn't in my imagination =D

**Comment by afh** [comment]
@hswolff @rowanj I agree the fade in/out animation is too much, using only the slide up/down animation gives a much better user experience.

**Pull request merged**
