### PR TITLE
Add script phase to correct ObjectiveGit linker references.

### LINKED ISSUE #207: Latest autoupdate breaks gitx
On OS X 10.8.4.
Version: 0.14.89 dev

```
dyld: Library not loaded: @rpath/ObjectiveGit.framework/ObjectiveGit
  Referenced from: /usr/local/bin/gitx
  Reason: image not found
Trace/BPT trap: 5
```

### PR DESCRIPTION
**Pull request by tiennou**
Fixes #207

### CODE REVIEW

**Comment by rowanj** [comment]
The runtime link path should just be set in the project options; see 3b0af682450bf4bfec4e172ebc230b998a5fd87c

**Comment by tiennou** [comment]
Nice ! It's been a while since I had to `install_name_tool` stuff around, so it's a welcome addition that web can now _change a framework/library install path without having to muck with its Xcode project_. Yay !

The other commit is just a really quick fix while you were off, but I'm pretty sure it leaks :-S.

**Comment by tiennou** [comment]
Oh, and I think the appearance of #207 is related to a change in ObjectiveGit configurations, but I'm not sure (the weird `@rpath/ObjectiveGit.framework/ObjectiveGit` come from it).

**Comment by rowanj** [comment]
Should be fixed in 0.14.95; I cherry-picked the 10.7 fix from this branch, thanks very much.

**Pull request closed without merging**
