### PR TITLE
Patch/fix sidebar template icons

### PR DESCRIPTION
**Pull request by nanoant**
1. Removes unnecessary highlighted sidebar image versions and make all other to use plain black (alpha only)
2. Removed unused icon source files (this are anyway accessible in Git history)
3. Uses `NSImageCell` for applying actual effect, which makes proper proper overlay effect depending on platform
4. Introduces pixel aligned PDF (scale independent icons) icons that preserve style of @afh previous commit, however give SVG source (instead Pixelmator which is proprietary), for details see cd94264
5. Uses SVG pixel aligned icons for history file icons, which makes them look sharp on all displays

### CODE REVIEW

**Comment by nanoant** [comment]
Here I am attaching preview of how it looked before and how it looks when applying changes above.

Make sure you click on _Before_ & _Now_ and switch tabs to compare.

### Before

old alexis

### Now

new pdf

### Now (Retina)

new pdf retina

**Comment by rowanj** [comment]
Looks great; I'm excited to merge this when I've got a few more of the 0.15 launch bugs sorted out.

:thumbsup:

**Comment by nanoant** [comment]
Rebased to latest `master`.

**Comment by rowanj** [comment]
Thanks for the rebase; love it!

**Pull request merged**
