### PR TITLE
Loading performance

### PR DESCRIPTION
**Pull request by ghost**
Fixes for issue #157

### CODE REVIEW

**Comment by barnabyc** [comment]
Any chance of a review and/or merge here? Would love to get some performance improvements! /cc @rowanj

**Comment by osheroff** [comment]
I too desire this patch, made GitX once again usable on a repo with lots of branches.

**Comment by bquorning** [comment]
Improved performance FTW. Please merge!

**Comment by marcalc** [comment]
+1

**Comment by rowanj** [comment]
Reviewing now.

**Comment by barnabyc** [comment]
Thank you @rowanj! :smile:

**Comment by rowanj** [comment]
@barnabyc Glad you're excited about it!

I'll try to get another point release out tonight, but if it doesn't go smoothly it'll have to wait a day or so; it's already after 1 AM here ^_^

**Comment by rowanj** [comment]
It went smoothly.  This is in 0.14.83

**Comment by barnabyc** [comment]
Awesome, thank you again! Now get some sleep!

**Comment by bquorning** [comment]
Wow, it's _so_ much faster now. Thank you!

## 

Benjamin

**Comment by ghost** [comment]
cool, thank you for the merge and for releasing it right away!

**Comment by rowanj** [comment]
@micampe Thanks for the code! Running it made such a difference that I couldn't bear to sit on it :-)

**Pull request closed without merging**
