### PR TITLE
Stash support

### PR DESCRIPTION
**Pull request by tiennou**
This is a rebase of #239 on top of #301. It might be possible to have it against master if you prefer, but I felt compelled to force your hand a little ;-).

Notes :
- I rewrote commits on the fly while rebasing (because of the XIBs and conflicts) so some of the originals are slightly changed (eg. 73cf163 switched to using the Objective-Git wrapper directly).
- Objective-Git still lacks support for `stash pop`, so I didn't switch it away from the CLI at all. I _might_ go do some C for this ;-).

### CODE REVIEW

**Comment by tiennou** [comment]
Oh yeah, fixes #14, #424.

**Comment by tiennou** [comment]
Looks like the C part is cooking in in https://github.com/libgit2/libgit2/pull/2705.

**Comment by jakirkham** [comment]
+1

Better stash support would be amazing.

**Comment by rad182** [comment]
why hasn't this merged yet?:(

**Comment by eapen** [comment]
👍

**Pull request closed without merging**
