### PR TITLE
Add newly designed retina display icons

### PR DESCRIPTION
**Pull request by afh**
I have created some new icons based on [Font Awesome](http://fortawesome.github.io/Font-Awesome/) to support retina displays.

Before completing the new icon set I'd like to know whether a redesign would be appreciated and whether it goes into the right direction.

Please let me know what you think.

### CODE REVIEW

**Comment by hswolff** [comment]
You have a picture of these in use I can see per-chance?  The words 'support retina' is like sweet honey to my ears.

**Comment by afh** [comment]
Unfortunately I brought my MacBook Pro Retina Display to the Apple Store today to have it repaired,
and did not create a screenshot beforehand, bummer.

Additionally I see, that I need to rearrange my git tree, since in this merge request there are
several old commits, that are not related to the newly redesigned icons changes

**Comment by rowanj** [comment]
Very interesting stuff, though!

**Comment by rowanj** [comment]
On non-retina: screen shot 2013-06-03 at 12 12 28 pm

The new sidebar items look great - the local branch light-green might be a bit too subtle on the blue background.

I think the add branch and add tag buttons look a little fuzzy, and possibly out-of-aspect; I'll double check the size they're being presented at matches the source.

**Comment by rowanj** [comment]
@afh In general, I love the new design; though  :+1:

**Comment by afh** [comment]
@rowanj Glad you love the new design and thanks for cherry-picking the commit :)

I'm having my MacBook Pro Retina Display repaired, so I'll be working on a non-retina display, which is a great opportunity for me to improve the non-retina icons.

I will correct the the file sizes of the non-retina icons that I forgot to scale down (e.g. AddBranchTemplate).
Which other icons are used that could use a revamp?

**Comment by rowanj** [comment]
@afh I've merged the cherry pick, so I'm closing this issue for now.

The new icons look much better; although I would definitely accept any more tweaks you have to offer, and scaled-down versions of the appropriate icons.

As for things that could use a revamp; the tetail/tree view buttons (right-most group in the toolbar) now seem like the line weighting isn't heavy enough, compared with the others.

I was talking with @jamescuda (interface designer at my [day job](http://savage.si/)) this afternoon, and  he pretty convincingly stated that there was little in favour of most of the current layout and graphics; with a particular distaste for the main app icon.  I'd love to see any ideas you have there (either of you ;-) )

**Comment by Uncommon** [comment]
I agree that the green part of the new branch icon doesn't stand out enough against the background.

**Comment by afh** [comment]
@rowanj I'll make further tweaks and provide scaled-down versions, now that I have my retina display laptop back.
Thanks for the the list of things that could use a revamp, I see what I can do : )

**Comment by nanoant** [comment]
Hi. If we really want to replace old icons, can we [pixel align](http://dcurt.is/pixel-fitting) **all** new icons first? Unfortunately on non-retina displays (iMac) new icons look really blurry comparing to old (pixel-aligned) ones.

new(new) old(old)

I'd also suggest to make sidebar icons to be Template ones (so they get proper sidebar inset effect and inverse color for selected item) rather than making different set for highlighted icons and trying to mimic Lion monochromatic look. Using Template icons makes this look default. 

Also it would be fine to use Mac icons for folders, not custom ones, see:
`/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/GenericFolderIcon.icns`
`/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/SidebarGenericFolder.icns` (>=10.7 sidebar)

Finally the toolbar icons are little bit too high as for the round gradient buttons, especially comparing to built-in log vs file list switch buttons.

**Comment by afh** [comment]
Yes, all new icons should be pixel aligned, I can convert the font glyphs to vectors (shapes) within Pixelmator and then follow the steps outlined in your aforementioned [article](http://dcurt.is/pixel-fitting).

I do prefer custom folder icons over the ones provided by the system, I think this gives a much more consistent look throughout the whole application.

Regarding sidebar template icons:
The [Designing Sidebar Icons](https://developer.apple.com/library/mac/documentation/userexperience/conceptual/applehiguidelines/IconsImages/IconsImages.html#//apple_ref/doc/uid/20000967-SW3) section in the [OS X HIG](https://developer.apple.com/library/mac/#documentation/userexperience/conceptual/applehiguidelines/Intro/Intro.html#//apple_ref/doc/uid/TP30000894-TP6) and [SidebarDemo](http://developer.apple.com/library/mac/#samplecode/SidebarDemo/Introduction/Intro.html) sample code provide all the information that is needed.

I'll have a look to see what would need to be changed.

@rowanj Would these kind of changes be acceptable?

**Comment by rowanj** [comment]
@afh I welcome many changes (and screenshots, where they change graphics/layouts); I also welcome the input of the precious few others who trawl through the various comments and bug reports, but in general if it doesn't make GitX slower, harder to use, or less discoverable it stands an excellent chance of being merged.

I've just re-activated the project wiki (had been disabled since I forked from pieter), I guess I should consider adding some interface design/planning/mockup pages to that, eh.

**Comment by afh** [comment]
@rowanj that sounds very good. I've already experimented a bit with a view based sidebar, for odd reasons it crashes. I will issue a pull request when it is ready for review.

Yes, adding some interface design/planning/mockup/resources wiki pages is a good idea to exchange ideas and I'd love to contribute to that, is it [this one](https://github.com/rowanj/gitx/wiki/Design)?

Oh and congratulations on winning the [ADA](https://developer.apple.com/wwdc/events/awards/)!

**Comment by rowanj** [comment]
@afh Thanks very much, I'm sure we'll all have our work cut out for us over the next few weeks.

I see that Design page as a general overview, not necessarily specific to interface stuff, but if you've got something that fits, please; add it!  Also feel free to create a more specific design/mockup wiki page if you've got stuff to contribute there, or if you have something specific in mind just create an issue (which may allow better tracking of comments/changes anyway); it's up to you.

**Comment by afh** [comment]
@rowanj Ok I'll create a new wiki page or open an issue as I see fit, to advance on the icon redesign.

**Pull request closed without merging**
